apiVersion: v1
kind: Service
metadata:
  name: cloud-demo
  labels:
    app: cloud-demo
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: cloud-demo
#  type: ClusterIP
#  ports:
#    - port: 8080
#  selector:
#    app: cloud-demo
